export const ACTION_SET_DARKMODE = 'SET_DARK_MODE';
export const ACTION_SET_PHONEOTICS_STATUS = 'SET_PHONEOTICS_STATUS';

//temp
export const ACTION_SET_TEMP_WORDS = 'SET_TEMP_WORDS';
export const ACTION_SET_TEM_HISTORY = 'SET_TEMP_HISTORY';
export const ACTION_SET_TEMP_SAVED = 'SET_TEMP_SAVED';
